<?xml version="1.0"?>
<package format="2">
  <name>cube_bathymetry</name>
  <version>0.0.0</version>
  <description>Generate a bathymetric surface using UNH CCOM's CUBE algorithm</description>

  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>grid_map_ros</depend>
  <build_depend>libgdal-dev</build_depend>
  <depend>project11</depend>
  <!-- <depend>rosbag</depend> -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
